### ISSUE TITLE
Module's run method are executed more than once

### ISSUE THREAD

**Issue by william26** [william26/je-di#33]
When a module is given as dependency for several modules, its `.run()` method is executed once for every dependency.

**Comment by TheVinc** [comment]
I expect this bug to cause many disagreements. 
I have encounter some use cases where two `.run()` that require the same service dependency prevent it to register information at run time, thus causing the service to be empty when later used by another factory. 
It is very annoying ;___; 
@william26 plz fix it! You would be a hero!

**Comment by william26** [comment]
Resolved by #37 

But this will cause major problems in the future that we need to fix in 2.0.0
